AWSTemplateFormatVersion: 2010-09-09
Description: >
  This templates demonstrates the creation of a simple S3. 
  bucket. It allows for parameterising the bucket name and
  a few other attributes.
Parameters:
  BucketName: 
    Type: String
    Description: The name of the bucket.
Resources:
  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      BucketEncryption: 
        ServerSideEncryptionConfiguration: 
        - ServerSideEncryptionByDefault:
            SSEAlgorithm: AES256    
      Tags:
      - Key: Name
        Value: !Join ['', [!Ref "AWS::StackName", "-Bucket"]]
  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref Bucket
      PolicyDocument:
        Statement:
        - Sid: DenyUnEncryptedObjectUploads
          Effect: Deny
          Principal: "*"
          Action: s3:PutObject
          Resource:
            Fn::Join:
            - ''
            - - 'arn:aws:s3:::'
              - Ref: BucketName
              - "/*"
          Condition:
            StringNotEquals:
              s3:x-amz-server-side-encryption: AES256
