AWSTemplateFormatVersion: 2010-09-09
Description: >
  This template can be used to create a simple S3
  bucket. It allows for parameterising the bucket name and
  a few other attributes.
Parameters:
  BucketName:
    Type: String
    Description: The name of the bucket.
  BucketVersioning:
    Type: String
    Default: Suspended
    AllowedValues:
      - Enabled
      - Suspended
    Description: The versioning configuration for the bucket.
  BucketAccessControl:
    Type: String
    Default: Private
    AllowedValues:
      - Private
      - PublicRead
      - PublicReadWrite
      - AuthenticatedRead
      - LogDeliveryWrite
      - BucketOwnerRead
      - BucketOwnerFullControl
      - AwsExecRead
    Description: Access control configuration for the bucket (default is Private).
Resources:
  Bucket:
    Type: AWS::S3::Bucket
    Properties: 
      BucketName: !Ref BucketName
      Tags:
        - Key: Name
          Value: !Join ['', [!Ref "AWS::StackName", "-Bucket"]]
      AccessControl: !Ref BucketAccessControl
      VersioningConfiguration: 
        Status: !Ref BucketVersioning
Outputs:
  BucketName: 
    Value: !Ref Bucket
    Description: The name of the bucket.
  BucketDomainName:
    Value: !GetAtt Bucket.DomainName
    Description: The DNS domain name of the bucket.
  BucketRegionalDomainName:
    Value: !GetAtt Bucket.RegionalDomainName
    Description: The domain name including the AWS Region where the bucket is located.
  BucketArn:
    Value: !GetAtt Bucket.Arn
    Description: The Amazon Resource Name (ARN) of the bucket.
